[2025-07-31T19:33:50.301+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline_example.check_table_exists manual__2025-07-31T19:33:47.869280+00:00 [queued]>
[2025-07-31T19:33:50.311+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline_example.check_table_exists manual__2025-07-31T19:33:47.869280+00:00 [queued]>
[2025-07-31T19:33:50.312+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-07-31T19:33:50.325+0000] {taskinstance.py:1380} INFO - Executing <Task(BranchPythonOperator): check_table_exists> on 2025-07-31 19:33:47.869280+00:00
[2025-07-31T19:33:50.329+0000] {standard_task_runner.py:57} INFO - Started process 875 to run task
[2025-07-31T19:33:50.333+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline_example', 'check_table_exists', 'manual__2025-07-31T19:33:47.869280+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpm8ivnyms']
[2025-07-31T19:33:50.336+0000] {standard_task_runner.py:85} INFO - Job 250: Subtask check_table_exists
[2025-07-31T19:33:50.386+0000] {task_command.py:415} INFO - Running <TaskInstance: postgres_pipeline_example.check_table_exists manual__2025-07-31T19:33:47.869280+00:00 [running]> on host 39aa5c3cd22d
[2025-07-31T19:33:50.471+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline_example' AIRFLOW_CTX_TASK_ID='check_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T19:33:47.869280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T19:33:47.869280+00:00'
[2025-07-31T19:33:50.481+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-07-31T19:33:50.485+0000] {sql.py:418} INFO - Running statement: SELECT 1 FROM information_schema.tables WHERE table_name = %s, parameters: ['user_processing_data']
[2025-07-31T19:33:50.488+0000] {sql.py:427} INFO - Rows affected: 1
[2025-07-31T19:33:50.489+0000] {logging_mixin.py:151} INFO - Table check for 'user_processing_data' returned: (1,)
[2025-07-31T19:33:50.489+0000] {python.py:194} INFO - Done. Returned value was: insert_row
[2025-07-31T19:33:50.490+0000] {python.py:227} INFO - Branch callable return insert_row
[2025-07-31T19:33:50.490+0000] {skipmixin.py:173} INFO - Following branch insert_row
[2025-07-31T19:33:50.505+0000] {skipmixin.py:239} INFO - Skipping tasks [('create_table', -1)]
[2025-07-31T19:33:50.546+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline_example, task_id=check_table_exists, execution_date=20250731T193347, start_date=20250731T193350, end_date=20250731T193350
[2025-07-31T19:33:50.595+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-31T19:33:50.633+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
